services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: monitordb
      POSTGRES_USER: monitoruser
      POSTGRES_PASSWORD: monitorpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  mosquitto:
#    image: eclipse-mosquitto:2
#    ports:
#      - "1883:1883"
#    volumes:
#      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

#  backend:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
#      - mosquitto
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/monitordb
#      SPRING_DATASOURCE_USERNAME: monitoruser
#      SPRING_DATASOURCE_PASSWORD: monitorpassword
#      MQTT_BROKER: tcp://mosquitto:1883

volumes:
  postgres_data:
